# Uncomment the next line to define a global platform for your project
# platform :ios, '12.4'
target 'LibrariesExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftGen'
  pod 'SwiftLint'
end
